In [6]:
import numpy as np
# array creation

In [10]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
a = [1,2,3,"Qasim",3.5]
a

[1, 2, 3, 'Qasim', 3.5]

In [13]:
np.array(a)

array(['1', '2', '3', 'Qasim', '3.5'], dtype='<U32')

In [23]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(l)

# array generation function

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [29]:
arr = np.zeros((7,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
# linspacea
arr = np.linspace(0,1,100)
arr
#  linear space space same rhti ha 

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [38]:
# random number generation 

In [42]:
np.random.rand(10)

array([0.72789087, 0.20313185, 0.75035873, 0.94267685, 0.08812637,
       0.48939464, 0.80526395, 0.83641522, 0.0120831 , 0.22945497])

In [47]:
np.random.randn(10)
               

array([ 0.26940934, -0.09357801, -1.6491502 ,  0.65564179,  0.89739905,
       -0.06082101, -0.93644968,  0.96826953,  0.62045525,  1.17074129])

In [51]:
np.random.randint(10,20,10)

array([11, 10, 10, 15, 13, 17, 17, 15, 12, 11], dtype=int32)

In [52]:
# Array Attributes 

In [53]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.shape

(3, 3)

In [55]:
arr.size

9

In [56]:
arr.dtype

dtype('int64')

In [57]:
# Array method 

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr.min()

np.int64(1)

In [60]:
arr.max()

np.int64(9)

In [61]:
arr.sum()

np.int64(45)

In [63]:
arr = np.sum(arr,axis=0)
arr

np.int64(45)

In [64]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [67]:
arr.mean()

np.float64(5.0)

In [68]:
arr.std()

np.float64(2.581988897471611)

In [69]:
arr.argmax()

np.int64(8)

In [70]:
arr.argmin()

np.int64(0)

In [71]:
#  reshaping and resizing

In [73]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [74]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [77]:
arr = np.resize(6,5)


In [79]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [81]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [82]:
arr = arr.reshape(6,5)

In [83]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])