In [3]:
import numpy as np

In [4]:
# ARRAY OPERATIONS 
# Arithmatic operations

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [6]:
arr = a1 + a2
arr

array([ 7,  9, 11, 13, 15])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [11]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [12]:
#  Broadcasting

In [13]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [14]:
arr + 10

array([20, 30, 40, 50])

In [15]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr2 = arr2 + 10

In [17]:
arr2 * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [18]:
#  Deep and Shallow copy

In [19]:
#  shallow copy
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a[3:6] * 10

array([40, 50, 60])

In [23]:
a[3:6]

array([4, 5, 6])

In [24]:
a
b=a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
#  Matrix Operation

In [28]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [29]:
B

array([[5, 6],
       [7, 8]])

In [30]:
A@B   # multiply matrix

array([[19, 22],
       [43, 50]])

In [31]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [32]:
A.T

array([[1, 3],
       [2, 4]])

In [33]:
B.T

array([[5, 7],
       [6, 8]])

In [34]:
#  ADVANCE ARRAY MULTIPLICATION 

# stacking array

In [35]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [36]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.column_stack((a,b))


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [39]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [44]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [45]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
