In [ ]:
# Valid Sudoku
import numpy as np 

In [ ]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8], 
    [1,9,8,3,4,2,5,6,7], 

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])


In [ ]:
s.sum()

np.int64(405)

In [ ]:
b = np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break

else:
    print("for rows it is valid ")

for rows it is valid 


In [ ]:
c = np.sum(s,axis=0)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for column it is valid ")

for column it is valid 


In [ ]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])



[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = (s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
data = np.array([
    # colums :[age,marth marks, science marks]
    [18,85,78], #student1
    [19,92,88], #student2
    [17,76,95], #student3
    [18,65,70], #student4
    [20,90,85] #student5
])

In [ ]:
data.shape
# find matrix

(5, 3)

In [ ]:
np.mean(data[:,0])
# average of students age

np.float64(18.4)

In [ ]:
data[:,1]
# extract math marks


array([85, 92, 76, 65, 90])

In [ ]:
#find the highest science marks
np.argmax(data[:,2])

np.int64(95)

In [ ]:
#get details of the students who scored more than 90 in math 
data[data[:,1]>90]
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# increase math marks of all students by 5
data[:,1] += 5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [ ]:
# find how many students are younger then 19
len(data[data[:,0] < 19])

3

In [ ]:
# average find in each subject (column-wise mean),
np.mean(data[:,1:],axis=0)




array([86.6, 83.2])

In [ ]:
# get data of students who scored at least 80 in both subjectabs
data[(data[:,1] >= 80) & (data[:,2] >= 80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [ ]:
# replace all science marks < 75 with 0abs
data[:,2] [data[:,2] < 75] = 0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])